version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
build:
  os: ubuntu-20.04  # Specify the desired OS version (e.g., Ubuntu 20.04)
  tools:
    python: "3.10"  # Specify your Python version as a string
  apt_packages:
    - libboost-dev
  jobs:
    pre_install:
      - pip install swig boost h5py
      - pip install -r docs/requirements.txt