version: 2
build:
  os: ubuntu-20.04  # Specify the desired OS version (e.g., Ubuntu 20.04)
  tools:
    python: "3.10"  # Specify your Python version as a string
  jobs:
    pre_install:
      - curl -fsSL https://ftp-master.debian.org/keys/archive-key-12.asc -o /tmp/debian-archive-keyring.asc
      - curl -fsSL https://ftp-master.debian.org/keys/archive-key-12-security.asc -o /tmp/debian-security-archive-keyring.asc
      - wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz -O boost_1_76_0.tar.gz
      - tar -xvzf boost_1_76_0.tar.gz
      - cd boost_1_76_0
      - ./boost_1_76_0/bootstrap.sh --prefix=$HOME/.local  # Install Boost locally
      - ./boost_1_76_0/b2 install --prefix=$HOME/.local
      - ./boost_1_76_0/b2 headers --prefix=$HOME/.local
      - export BOOST_ROOT=$HOME/.local  # Set BOOST_ROOT environment variable
      - export BOOST_INCLUDEDIR=$BOOST_ROOT/include  # Ensure Boost headers are found
      - export BOOST_LIBRARYDIR=$BOOST_ROOT/lib  # Ensure Boost libraries are found
      - cd ..
      - pip install swig boost h5py
      - ls $HOME/.local/include/boost/shared_ptr.hpp
      - pip install -r docs/requirements.txt