version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  
  before_install:
    # Install system dependencies (SWIG and Boost)
    - sudo apt-get update
    - sudo apt-get install -y swig libboost-all-dev

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
