version: 2
build:
  os: ubuntu-20.04  # Specify the desired OS version (e.g., Ubuntu 20.04)
  tools:
    python: "3.10"  # Specify your Python version as a string
  jobs:
    pre_install:
      - pip install cmake  # Install CMake
      # Install Homebrew (if necessary) and SWIG
      - export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"  # Update the PATH for Homebrew (Linux)
      - which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  # Install Homebrew if it's not already installed
      - brew install swig  # Install SWIG using Homebrew
      # Install Boost from source
      - wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz  # Replace with the latest Boost version if necessary
      - tar -xvzf boost_1_76_0.tar.gz
      - cd boost_1_76_0
      - ./bootstrap.sh --prefix=$HOME/.local  # Specify the local installation directory
      - ./b2 install
      - export BOOST_ROOT=$HOME/.local  # Set the BOOST_ROOT environment variable
