[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[project]
name = "lumache"
authors = [{name = "Peter Cauchy", email = "peter.cauchy@test.com"}]
dynamic = ["version", "description"]