[tool.poetry]
name = "project-chameleon"
version = "0.1.0"
description = "A package for transforming and querying different file formats commonly found in material science research"
authors = ["Peter Cauchy"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.9.0"
numpy = "^1.26.4"
hyperspy = "^2.1.0"
py4DSTEM = "^0.14.15"
xylib-py = "^1.6.1"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
non4dstem = "project_chameleon.nonfourdimension_stem.non4dstem:main"
stemarray4d = "project_chameleon.fourdimension_stem.stemarray4d:main"
mbeparser = "project_chameleon.MBE.mbeparser:main"
ppmsmpms = "project_chameleon.ppmsmpms.ppmsmpms:main"
rheed = "project_chameleon.RHEED.rheedconverter:main"
brukerraw = "project_chameleon.XRD.BrukerRAW.brukerrawconverter:main"
brukerrawbackground = "project_chameleon.XRD.BrukerRaw.brukerrawbackground:main"