package:
  name: chameleon
  version: "1.0.0"

source:
  path: ../

build:
  number: 0
  script: |
    mkdir -p build
    cd build
    cmake ..
    make
    make install

    git clone https://github.com/wojdyr/xylib.git
    cd xylib
    mkdir build
    cd build
    cmake ..
    make
    make install

    cp -r ../project_chameleon $PREFIX/lib/python$PY_VER/site-packages/chameleon
    cp -r ../data $PREFIX/lib/python$PY_VER/site-packages/data


  matrix:
    - os: osx
      arch: x86_64
    - os: osx
      arch: arm64

requirements:
  build:
    - python=3.12
    - git
    - clang
    - swig
    - hdf5
    - pkg-config
    - libboost
    - pip
    - make  # For build-essential
    - cmake  # For build-essential


  host:
    - python=3.12
    - pip

  run:
    - python=3.12
    - uvicorn
    - fastapi
    - matplotlib
    - numpy
    - hyperspy
    - py4dstem
    - pandas
    - hdf5
    - libboost
    - pip

test:
  imports:
    - chameleon
    - xylib
  commands:
    - python -c "import chameleon"
    - python -c "import xylib"

about:
  home: chameleon

channels:
  - conda-forge
  - defaults
